# Site
name: 'Animiojo'
description: 'Animiojo. Resumo de episódios de animes em 3 minutos.'
logo: 'assets/images/animiojo/animiojo_2025_88.png'
favicon: 'assets/images/animiojo/animiojo_2025_180.png'
baseurl: ''
host: 'www.animiojo.com'
avatar: 'assets/images/animiojo/animiojo_2025_88.png'
disqus: 'animiojo-2025'
email: 'animiojo@animiojo.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]